### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ext4zzzy** [olesya1119/SQLInterpreter#3]

**Comment by WinGKuza** [comment]
Перед нами стояла задача сделать SQL интерпретатор, не используя уже готовые решения/библиотеки.
Это означает, что нужно было самим распарсить команды (готовыми парсерами также пользоваться запрещено),
после этого использовать уже работу с файлами, которые имеют специфическую структуру. Сторонние БД использовать нельзя. В проекте используются два вида файлов для хранения информации:
1) dbf - файлы (это основной файл, в котором хранится информация)
2) dbt - файлы (это вспомогательный файл, в котором может храниться большой текст (используется в MEMO полях))
Если ты найдешь какие-либо баги в этом проекте, то мы будем рады их исправить.

Единственное что, я не понимаю, как ты представляешь работу с таким проектом без выкладывание его на GitHub? Проект был рассчитан на 5 человек (пятый человек делал всю бумажную работу). Предложи другой удобный вариант работы с таким проектом 4 людям, чтобы можно было обмениваться кодом + фиксить ошибки + добавлять новые команды + соединять разные куски программы.

**Comment by WinGKuza** [comment]
Кстати, я бы написал бы тебе проблемы твоего проекта, если бы ты открыл возможность их оставлять.

**Comment by ext4zzzy** [comment]
Открыл😀

**Comment by ext4zzzy** [comment]
Мои предложения тут: https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/coding-conventions https://metanit.com/sharp/patterns/5.1.php  Вместо вашего класса Date, можно использовать структуру DateTime + всё в одном проекте лежит

**Comment by WinGKuza** [comment]
Нам легче было сделать свой Date в момент написания. Я понимаю, что можно использовать вариант и с DateTime. Но это не является критичной ошибкой.
В проекте могут нарушаться некоторые принципы SOLID, но это всё не является обязательными условиями в написании кода, это лишь рекомендации по написанию кода.
По стилю кода я не ручаюсь за других людей, но я стараюсь соблюдать их.

**Comment by WinGKuza** [comment]
Ты не открыл.
"An owner of this repository has limited the ability to open an issue to users that are collaborators on this repository."

**Comment by ext4zzzy** [comment]
Смысл такого хардкодинга? и чем ваш класс лучше и легче встроенной библиотеки, которая не перегружает код?
Открыл ишью

**Comment by WinGKuza** [comment]
Я не говорил, что он лучше. Он просто выполняет все нужные нам действия.
Возможно можно переписать код, использовать DataTime, но он не будет давать дату и время в нужном нам формате. Если хочешь, то можешь заняться этим.

**Comment by TheActualTwinkle** [comment]
Это не нужные действия, это **war crime!**
